<!DOCTYPE html>
<html>
<head>
    <h1>Login</h1>
</head>
<body>
<form action="login/auth" method="post">
    <table>
        <tr>
            <td>
                Email Address:
            </td>
            <td>
                <input type='mail'  name='email' value="">
            </td>
        </tr>
        <tr>
            <td>
                Password:
            </td>
            <td>
                <input type='password' name='password' value="">
            </td>
        </tr>
    </table>
    <br>
    <input type="submit" value="Login">
</form>
</body>
</html>