<?php
/** @var \App\Models\Post[] $posts */
$posts = $this->posts;
$isAdmin = $_SESSION['admin'];
?>

<h1>
    Blog!!!
</h1>
<br>
<br>
<form enctype="multipart/form-data" action="/blog/addMessage" method="post">
    Message:<br>
    <textarea name="text" style="width: 250px; height: 100px;"></textarea><br>
    Прикрепить картинку:<br><br>
    <input type="file" name="image" /><br><br>
    <input type="submit" value="Send">
</form>

<?php foreach ($posts as $post): ?>
    <div class="post">
        <div class="message"><?=$post->getText();?></div>
        <?php if($post->getImage()):?>
            <div><img src="/images/<?=$post->getImage();?>" style="width: 150px;"></div>
        <?php endif;?>
    </div>
    <?php if($isAdmin): ?>
        <div>
            <a href="/admin/deleteMessage/?id=<?=$post->getId();?>">delete</a>
        </div>
    <?php endif; ?>
<?php endforeach;?>

<style>
    .post {
        border: 1px solid grey;
        margin-top: 10px;
        padding: 5px;
        width: 250px;
    }

    .message {
        margin-top: 5px;
        padding-left: 5px;
    }
</style>